name: FFAGames
main: fr.razi.ffagame.FFAGame
version: 1.1
author: Razi
commands:
  lobby:
    description: Teleports you to the lobby.
    usage: "/lobby"
  world:
    description: Shows your current world and lets you teleport to a defined location.
    usage: "/world"